#!/usr/bin/env bash

SERVICE='hyperf-example'

function service_name {
  echo ${SERVICE}
}

# start containers
function start {
  docker-compose up -d --build
}

# restart containers
function restart {
  docker-compose restart
}

# stop containers
function stop {
  docker-compose stop
}

# initialize application
function init {
  echo "Stating Initialization..."

  echo "Copy .env file..."
  cp -n .env.example .env

  echo "Build docker images..."
  docker-compose build

  echo "Initialization completed!"
}

# login to container
function login {
  echo "Attempt to login ${SERVICE} container..."
  docker-compose exec ${SERVICE} bash
}

# show container logs
function logs {
  docker-compose logs $1
}

function init_db {
  docker-compose exec ${SERVICE} sh -c 'php bin/hyperf.php migrate:install'
  migrate
  docker-compose exec ${SERVICE} sh -c 'php bin/hyperf.php db:seed'
}

function migrate {
  docker-compose exec ${SERVICE} sh -c 'php bin/hyperf.php migrate $1'
}

function help {
  echo "    service_name"
  echo "    start"
  echo "    restart"
  echo "    stop"
  echo "    init"
  echo "    login"
  echo "    logs {optional container name}"
  echo "    migrate --force - optional"
}

subcommand=$1
shift

case $subcommand in
start)
  start $@
  ;;
restart)
  restart
  ;;
stop)
  stop
  ;;
init)
  init
  ;;
init_db)
  init_db
  ;;
login)
  login
  ;;
logs)
  logs $1
  ;;
install)
  install
  ;;
migrate)
  migrate $1
  ;;
service_name)
  service_name
  ;;
help)
  help
  ;;
*)
  echo "help"
  ;;
esac
